#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely and prints I am invincible!!! when receiving SIGTERM
trap 'echo "I am invincible!!!"; echo "OK"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
