#!/usr/bin/env bash
# Script that displays a message indefinitely and handles SIGTERM

# Trap SIGTERM and execute echo
trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
